### ISSUE TITLE
Syntax error - JSON Parse 

### ISSUE THREAD

**Issue by knsenthil** [elgentos/LargeConfigProducts#8]
@peterjaap @astorm 
My Configurable product has around 14k products associated. I have installed 
this module & I am getting this error. My Magento version 2.1.9. Is there anything i am missing ?
SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 5 column 35 of the JSON data
![lcp](https://user-images.githubusercontent.com/20596704/40663746-02aea24c-6377-11e8-8e9c-3f89f5d5abee.png)

kindly help me to get this resolved.

**Comment by knsenthil** [comment]
@peterjaap @astorm : Is there any update on this ?

**Comment by peterjaap** [comment]
Please paste the json here so we can see what's wrong with it.

**Comment by astorm** [comment]
@knsenthil Not my circus, not my monkeys -- but per @peterjaap's comments seeing the JSON  (maybe via the XHR debugger?) would be a prerequisite to helping out.

**Comment by knsenthil** [comment]
@peterjaap @astorm 
Here is the JSON
{
        "*": {
            "mage/cookies": {
                "expires": null,
                "path": "/magento2/magento219",
                "domain": ".localhost",
                "secure": false,
                "lifetime": "3600"
            }
        }
    }


        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        

    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": {"components":{"minicart_content":{"children":{"subtotal.container":{"children":{"subtotal":{"children":{"subtotal.totals":{"config":{"display_cart_subtotal_incl_tax":0,"display_cart_subtotal_excl_tax":1,"template":"Magento_Tax\/checkout\/minicart\/subtotal\/totals"},"children":{"subtotal.totals.msrp":{"component":"Magento_Msrp\/js\/view\/checkout\/minicart\/subtotal\/totals","config":{"displayArea":"minicart-subtotal-hidden","template":"Magento_Msrp\/checkout\/minicart\/subtotal\/totals"}}},"component":"Magento_Tax\/js\/view\/checkout\/minicart\/subtotal\/totals"}},"component":"uiComponent","config":{"template":"Magento_Checkout\/minicart\/subtotal"}}},"component":"uiComponent","config":{"displayArea":"subtotalContainer"}},"item.renderer":{"component":"uiComponent","config":{"displayArea":"defaultRenderer","template":"Magento_Checkout\/minicart\/item\/default"},"children":{"item.image":{"component":"Magento_Catalog\/js\/view\/image","config":{"template":"Magento_Catalog\/product\/image","displayArea":"itemImage"}},"checkout.cart.item.price.sidebar":{"component":"uiComponent","config":{"template":"Magento_Checkout\/minicart\/item\/price","displayArea":"priceSidebar"}}}},"extra_info":{"component":"uiComponent","config":{"displayArea":"extraInfo"}},"promotion":{"component":"uiComponent","config":{"displayArea":"promotion"}}},"config":{"itemRenderer":{"default":"defaultRenderer","simple":"defaultRenderer","virtual":"defaultRenderer"},"template":"Magento_Checkout\/minicart\/content"},"component":"Magento_Checkout\/js\/view\/minicart"}},"types":[]}        },
        "*": {
            "Magento_Ui/js/block-loader": "http://localhost:82/magento2/magento219/pub/static/version1527768131/frontend/Magento/luma/en_US/images/loader-1.gif"
        }
    }
    

{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": {"components":{"compareProducts":{"component":"Magento_Catalog\/js\/view\/compare-products"}}}}}


        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        

    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "messages": {
                            "component": "Magento_Theme/js/view/messages"
                        }
                    }
                }
            }
    }


    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": null<? /* @escapeNotVerified */ //echo $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": {"141":{"167":{"type":"0","value":"XS","label":"XS"},"168":{"type":"0","value":"S","label":"S"},"169":{"type":"0","value":"M","label":"M"},"170":{"type":"0","value":"L","label":"L"},"171":{"type":"0","value":"XL","label":"XL"}},"93":{"50":{"type":"1","value":"#1857f7","label":"Blue"},"56":{"type":"1","value":"#eb6703","label":"Orange"},"57":{"type":"1","value":"#ef3dff","label":"Purple"}}},
                "mediaCallback": "http://localhost:82/magento2/magento219/swatches/ajax/media/",
                "gallerySwitchStrategy": "prepend"
            },
            "Magento_Swatches/js/configurable-customer-data": {
                    "swatchOptions": null            }
        }
    }
My Version is 2.1.8. I think this module will work well in version 2.2.2. Is there any work around to make this working in 2.1.8 version. 
As per my analyse . I found "configurable-customer-data.js" file is missing in vendor -> module-swatches of Magento 2.1.8. Which is available in 2.2.2.

Kindly help me.

**Comment by peterjaap** [comment]
Could you fix the rendering of the json you pasted here? Or lint it yourself with https://jsonlint.com/ so you can check whether the JSON itself is indeed correct or not?

If not, you should trace the origin of the faulty JSON. Or get the JSON where it is still correct and compare the two.

**Comment by knsenthil** [comment]
@peterjaap : 

I fixed JSON error. Thank you. 

After that i found console saying ..
"TypeError: this._determineProductData is not a function" in "swatch-renderer-mixin.js".
I copy paste the same function found in "configurable-mixin.js" to "swatch-renderer-mixin.js".

Now getting the following error:

Loading failed for the <script> with source “http://localhost:82/magento2/magento219/pub/static/version1528718063/frontend/Magento/luma/en_US/Magento_Swatches/js/configurable-customer-data.js”

Error: Script error for: Magento_Swatches/js/configurable-customer-data
http://requirejs.org/docs/errors.html#scripterror

I am using magento 2.1.8 version . I don't find "configurable-customer-data.js" in Magento_Swatch module of Magento 2.1.8 version.

Kindly help me please.

![configurable-customer-data](https://user-images.githubusercontent.com/20596704/41230834-d332e834-6d9e-11e8-89ab-f56a83fd28f6.png)

**Comment by peterjaap** [comment]
~~@knsenthil that's weird, that file was added 2 years ago; https://github.com/magento/magento2/blame/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/ConfigurableProduct/view/frontend/layout/checkout_cart_configure_type_configurable.xml#L10~~

That file was added 7 months ago; https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Swatches/view/frontend/web/js/configurable-customer-data.js

You could try removing the mixin and see if that helps. Otherwise I'd advise you to upgrade.

**Comment by knsenthil** [comment]
@peterjaap : 
I installed 2.2.2 Magento Version on my local environment with sample data. I installed large config module & found no error on console.  But the product option wrapper is spinning infinitely. Am i missing anything ? 
![untitled](https://user-images.githubusercontent.com/20596704/41299024-279f8292-6e80-11e8-9926-5292b37f56e9.png)

**Comment by peterjaap** [comment]
@knsenthil have you configured redis?

**Comment by knsenthil** [comment]
no .. is there need to configure the redis ?

**Comment by peterjaap** [comment]
Yes, see the Readme

**Comment by knsenthil** [comment]
Its working perfectly in 2.2 version .. Thank you @peterjaap ..

**Comment by simonmaass** [comment]
@knsenthil I am having the same problem - could you maybe elaborate a bit more how u fixed the problem?
