### ISSUE TITLE
Compatibility with M2.3.3

### ISSUE THREAD

**Issue by gaiterjones** [elgentos/LargeConfigProducts#43]
I am testing this module with Magento 2.3.3.

Configurable variations are loading on the product page but I am seeing the following error in the console

```
widget.js:75 Uncaught TypeError: base is not a constructor
    at Function.$.widget (widget.js:75)
    at configurable-customer-data-mixin.js:7
    at mixins.js:87
    at Array.forEach (<anonymous>)
    at applyMixins (mixins.js:86)
    at mixins.js:106
    at Object.execCb (require.js:1650)
    at Module.check (require.js:866)
    at Module.<anonymous> (require.js:1113)
    at require.js:132
```

When I click on a swatch image the image does not load and the following error is shown

```
swatch-renderer-mixin.js:60 Uncaught TypeError: this.processUpdateBaseImage is not a function
    at $.<computed>.<computed>.updateBaseImage (swatch-renderer-mixin.js:60)
    at $.<computed>.<computed>.updateBaseImage (widget.js:100)
    at $.<computed>.<computed>._loadMedia (swatch-renderer.js:689)
    at $.<computed>.<computed>._loadMedia (widget.js:100)
    at $.<computed>.<computed>._OnClick (swatch-renderer.js:758)
    at $.<computed>.<computed>._OnClick (widget.js:100)
    at HTMLDivElement.<anonymous> (swatch-renderer.js:640)
    at HTMLDivElement.dispatch (jquery.js:5232)
    at HTMLDivElement.elemData.handle (jquery.js:4884)
```

I guess there are some changes in swatch-render.js causing problems. Is it possible to look at what we need to do to make this module 2.3.x compatible?

This would include some information regarding the renatocason/magento2-module-mq requirements. Are these still required by the module for 2.3.x?

This module makes a huge difference in cold cache loading times of configurable products and it would be great to get it working in 2.3.

**Comment by peterjaap** [comment]
Hi @gaiterjones, unfortunately I'm not maintaining this extension anymore since the client we wrote it for isn't with our company anymore.

I would be happy to merge PR's if you submit some.

The `renatocason/magento2-module-mq` is indeed still required. I set on a mission to replace it with the (in M2.3 introduced) messagequeue system of Magento itself but I never finished it (and I most likely never will): https://github.com/elgentos/LargeConfigProducts/issues/28 / https://github.com/elgentos/LargeConfigProducts/pull/29

**Comment by gaiterjones** [comment]
OK, thanks for the quick reply and the hard work you did to develop this module so far. I will take a look and see what I can do to get it working.

**Comment by sunilit42** [comment]
@gaiterjones  any update on this?

**Comment by gaiterjones** [comment]
@sunilit42 this was added in https://github.com/elgentos/LargeConfigProducts/pull/45

**Comment by sunilit42** [comment]
Hello @gaiterjones 

i am asking for widget.js:75 Uncaught TypeError: base is not a constructor
    at Function.$.widget (widget.js:75)
    at configurable-customer-data-mixin.js:7
    at mixins.js:87
    at Array.forEach (<anonymous>)
    at applyMixins (mixins.js:86)
    at mixins.js:106
    at Object.execCb (require.js:1650)
    at Module.check (require.js:866)
    at Module.<anonymous> (require.js:1113)
    at require.js:132

is that solved?

**Comment by gaiterjones** [comment]
What version are you testing with, I noticed there are some issues with swatch image swapping in 2.3.5 and 2.4.0. I also just noticed this change was not added as a release, so you should download the master code and not the release.

**Comment by sunilit42** [comment]
i m using 2.3.4

**Comment by gaiterjones** [comment]
It should work ok for 2.3.4. Did you install from the release or the master, as the last release is the old code.

**Comment by sunilit42** [comment]
i m trying to now install master code

**Comment by sunilit42** [comment]
swatch-renderer-mixin.js:60 Uncaught TypeError: this.processUpdateBaseImage is not a function

i am still getting this error

**Comment by sunilit42** [comment]
any solution for this?

**Comment by sunilit42** [comment]
i find that fix but still, price reload not working so checking

**Comment by gaiterjones** [comment]
I am using it in production on 2.3.3 and there are no errors. If I have time I will do some more tests with a new 2.3.5 install, the problem likely lies in changes to the core swatch renderer.

**Comment by gaiterjones** [comment]
Please try updating to my fork at https://github.com/gaiterjones/LargeConfigProducts I have updated the swatch renderer and  have tested in 2.3.5 and 2.4.0 

You can see it working here https://magento2.gaiterjones.com/en/bruno-compete-hoodie.html
